# Generated by Django 4.1.5 on 2023-02-01 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 7, 54, 43, 692889))),
                ('data_termino', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 7, 54, 43, 692889))),
            ],
        ),
    ]
