# Generated by Django 4.1.5 on 2023-02-01 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='presentes',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='aplicacao.presentes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 7, 58, 36, 873066)),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 7, 58, 36, 873066)),
        ),
    ]
